### PR TITLE
allow storing svg in external file

### PR DESCRIPTION
**Pull request by hall**
These changes add a `directory` setting, which, when set, saves the svg content to a generated UUID filename in that directory and writes a markdown image link to the file (e.g., ``). When set to a blank string (the default), the previous behavior of saving the svg content inline remains.

This helps declutter the markdown source and makes it easier to share images across documents.

Really cool project, by the way :slightly_smiling_face:

### CODE REVIEW

**Comment by zhaouv** [comment]
Exciting work! I will review and merge those in one or two week (I'm busy these days). And then I may do some small adjust.

**Comment by hall** [comment]
Sounds good :+1: no rush on my end. Time willing, I'll look at implementing a few more changes between now and then (e.g., setting up CI to publish the extension should be fairly straightforward and high-in-the-sky-not-sure-if-it's-even-possible-yet: palm rejection).

**Comment by dualer** [comment]
Can you give an example how to implement it when I want to save image in relative path directory? I want to combine with pandoc, and generate pdf file.

**Comment by zhaouv** [comment]
https://github.com/zhaouv/vscode-markdown-draw/blob/5d40d07d4ec0c52d0367fa1cc69ea3446d83447f/src/extension.js#L174-L181  
`path.join(vscode.workspace.rootPath, settings.directory)`  
`fs.writeFileSync(path.join(dir, filename), text, { encoding: 'utf8' })`

**Comment by dualer** [comment]
> https://github.com/zhaouv/vscode-markdown-draw/blob/5d40d07d4ec0c52d0367fa1cc69ea3446d83447f/src/extension.js#L174-L181
> 
> 
> `path.join(vscode.workspace.rootPath, settings.directory)`
> `fs.writeFileSync(path.join(dir, filename), text, { encoding: 'utf8' })`

Oh, the workspace path is not exact relative path. The exact relative path is the subdirectory of it. For example, I have a folder "work" in workspace, the exact relative path is `$(workspace)\work`.

**Comment by dualer** [comment]
The extension [Draw](https://github.com/hall/draw) work better in this point.

**Comment by zhaouv** [comment]
> The extension [Draw](https://github.com/hall/draw) work better in this point.

it is a fork of this extension. if you want some feature, you can make your own fork

**Pull request merged**
